### ISSUE TITLE
Schibsted login

### ISSUE THREAD

**Issue by mathiazom** [bendikrb/podme_api#1]
PodMe is transitioning to Schibsted login, and previous method will be removed this fall

https://podme.com/no/schibsted-faq

**Comment by bendikrb** [comment]
Thanks for the heads up! Guess we need to look in to this, then..
Note to self in that regard; https://techdocs.login.schibsted.com

**Comment by janpfo** [comment]
Is it possible to run this api with 2FA activated, or do I have to deactivate 2FA to make it work?
